# Generated by Django 5.0.2 on 2024-02-16 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_shopdata_tray_shopdata_note'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shop',
            new_name='Vendor',
        ),
        migrations.RenameModel(
            old_name='ShopData',
            new_name='VendorData',
        ),
        migrations.RenameField(
            model_name='vendordata',
            old_name='shop',
            new_name='vendor',
        ),
    ]
